#!/usr/bin/env tsx
// Generates CSS variables block and injects into src/app/globals.css

import fs from 'fs'
import path from 'path'
import { tokens } from './tokens'

function toKebab(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase()
}

function generateCssBlock(): string {
  const lines: string[] = ['  /* === Generated by design-system/generate-css.ts — DO NOT EDIT === */']

  // Colors
  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`  --color-${toKebab(key)}: ${value};`)
  }

  // Sidebar
  for (const [key, value] of Object.entries(tokens.sidebar)) {
    lines.push(`  --sidebar-${toKebab(key)}: ${value};`)
  }

  // Radius
  for (const [key, value] of Object.entries(tokens.radius)) {
    lines.push(`  --radius-${key}: ${value};`)
  }

  // Spacing
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --spacing-${key}: ${value};`)
  }

  // Typography
  for (const [key, value] of Object.entries(tokens.typography)) {
    lines.push(`  --typography-${toKebab(key)}: ${value};`)
  }

  return lines.join('\n')
}

const MARKER_START = '  /* === Generated by design-system/generate-css.ts — DO NOT EDIT === */'
const MARKER_END_PATTERN = /(\n  \/\* === END GENERATED === \*\/)/

const globalsPath = path.join(__dirname, '../src/app/globals.css')
let css = fs.readFileSync(globalsPath, 'utf-8')

const generatedBlock = generateCssBlock() + '\n  /* === END GENERATED === */'

// Replace existing block or inject into :root {}
if (css.includes(MARKER_START)) {
  const startIdx = css.indexOf(MARKER_START)
  const endMatch = css.indexOf('/* === END GENERATED === */')
  if (endMatch > -1) {
    const endIdx = endMatch + '/* === END GENERATED === */'.length
    css = css.slice(0, startIdx) + generatedBlock + css.slice(endIdx)
  }
} else {
  // Inject at start of :root block
  css = css.replace(':root {', `:root {\n${generatedBlock}`)
}

fs.writeFileSync(globalsPath, css)
console.log('✅ CSS variables generated successfully')
